# Cleaning the AML dataset

In [ ]:
# in terminal: uv sync
import pandas as pd
import numpy as np

In [2]:
# Loading the datasets

accounts = pd.read_csv('../../data/raw/HI-Small_accounts.csv')
trans = pd.read_csv('../../data/raw/HI-Small_Trans.csv')

In [4]:
accounts.head()

,Bank Name,Bank ID,Account Number,Entity ID,Entity Name
0,Portugal Bank #4507,331579,80B779D80,80062E240,Sole Proprietorship #50438
1,Canada Bank #27,210,809D86900,800C998A0,Corporation #33520
2,UK Bank #33,21884,80812BE00,800C47F50,Partnership #35397
3,Germany Bank #4815,32742,81047F300,80096F0B0,Corporation #48813
4,National Bank of Harrisburg,127390,80BD8CF00,800FB8760,Corporation #889

In [5]:
accounts.describe()

             Bank ID
count  518581.000000
mean   103425.510831
std    121479.549761
min         1.000000
25%     11107.000000
50%     32014.000000
75%    217096.000000
max    356303.000000

In [6]:
trans.head()

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0

## Atul's part

Cleaning tasks:
* separating the date-time column adn formatting it correctlu
* inserting two columns (`amount_received_euro` and `amount_paid_euro`) with the change in currency
* other---

## Sofia's part

Cleaning tasks:
* adding location columns for the banks
* other---